# Used only for testing local like production
# To start run: `npm run build` and then `docker compose up`
#  Not building inside docker so we don't have to mess with `git` access
# Cannot run at the same time as `npm start` as they use the same port.

services:
    nginx:
        image: nginx:alpine
        ports:
            - '3000:80'
        volumes:
            - ./public/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./build:/usr/share/nginx/html:ro
        restart: unless-stopped
