export enum CustomEvents {
    CAPTURE_TEST = 'Capture_Test',
    CAPTURE_CREATE = 'Capture_Create',
    CAPTURE_CREATE_CONFIG_CREATE = 'Capture_Create_Config_Create',
    CAPTURE_CREATE_CONFIG_EDIT = 'Capture_Create_Config_Edit',
    CAPTURE_DISCOVER = 'Capture_Discover',
    CAPTURE_EDIT = 'Capture_Edit',
    CAPTURE_MATERIALIZE_ATTEMPT = 'Capture_Materialize_Attempt',
    CAPTURE_MATERIALIZE_FAILED = 'Capture_Materialize_Failed',
    CAPTURE_MATERIALIZE_SUCCESS = 'Capture_Materialize_Success',
    MATERIALIZATION_CREATE = 'Materialization_Create',
    MATERIALIZATION_CREATE_CONFIG_CREATE = 'Materialization_Create_Config_Create',
    MATERIALIZATION_CREATE_CONFIG_EDIT = 'Materialization_Create_Config_Edit',
    MATERIALIZATION_TEST = 'Materialization_Test',
    MATERIALIZATION_EDIT = 'Materialization_Edit',
    NOTIFICATION_NETWORK_WARNING = 'Notification_Network_Warning',
    COLLECTION_CREATE = 'Collection_Create',
    DIRECTIVE = 'Directive',
    ERROR_BOUNDARY_DISPLAYED = 'Error_Boundary_Displayed',
    ERROR_BOUNDARY_PAYMENT_METHODS = 'Error_Boundary_Displayed:PaymentMethods',
    FULL_PAGE_ERROR_DISPLAYED = 'Full_Page_Error_Displayed',
    GATEWAY_TOKEN_FAILED = 'Gateway_Auth_Token:CallFailed',
    GATEWAY_TOKEN_INVALID_PREFIX = 'Gateway_Auth_Token:InvalidPrefix',
    STRIPE_FORM_LOADING_FAILED = 'Stripe_Form_Loading_Failed',
    SUPABASE_CALL_FAILED = 'Supabase_Call_Failed',
    SUPABASE_CALL_UNAUTHENTICATED = 'Supabase_Call_Unauthenticated',
    SWR_LOADING_SLOW = 'SWR_Loading_Slow',
}
