/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    mutation CreateAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n        $alertTypes: [AlertType!]\n        $detail: String\n    ) {\n        createAlertSubscription(\n            prefix: $prefix\n            email: $email\n            alertTypes: $alertTypes\n            detail: $detail\n        ) {\n            catalogPrefix\n            email\n        }\n    }\n": typeof types.CreateAlertSubscriptionMutationDocument,
    "\n    mutation DeleteAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n    ) {\n        deleteAlertSubscription(prefix: $prefix, email: $email) {\n            catalogPrefix\n            email\n        }\n    }\n": typeof types.DeleteAlertSubscriptionMutationDocument,
    "\n    query AlertSubscriptions($prefix: Prefix!) {\n        alertSubscriptions(by: { prefix: $prefix }) {\n            alertTypes\n            catalogPrefix\n            email\n            updatedAt\n        }\n    }\n": typeof types.AlertSubscriptionsDocument,
    "\n    mutation UpdateAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n        $alertTypes: [AlertType!]\n        $detail: String\n    ) {\n        updateAlertSubscription(\n            prefix: $prefix\n            email: $email\n            alertTypes: $alertTypes\n            detail: $detail\n        ) {\n            catalogPrefix\n            email\n        }\n    }\n": typeof types.UpdateAlertSubscriptionMutationDocument,
    "\n    query AlertType {\n        alertTypes {\n            alertType\n            description\n            displayName\n            isDefault\n            isSystem\n        }\n    }\n": typeof types.AlertTypeDocument,
    "\n    query ConnectorsGrid($filter: ConnectorsFilter, $after: String) {\n        connectors(first: 500, after: $after, filter: $filter) {\n            edges {\n                cursor\n                node {\n                    id\n                    imageName\n                    logoUrl\n                    title\n                    recommended\n                    shortDescription\n                    defaultSpec {\n                        id\n                        imageTag\n                        documentationUrl\n                        protocol\n                    }\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n": typeof types.ConnectorsGridDocument,
    "\n    query ConnectorTagData($imageName: String!, $fullImageName: String!) {\n        connector(imageName: $imageName) {\n            id\n            imageName\n            logoUrl\n            title\n        }\n        connectorSpec(fullImageName: $fullImageName) {\n            id\n            imageTag\n            defaultCaptureInterval\n            disableBackfill\n            documentationUrl\n            endpointSpecSchema\n            resourceSpecSchema\n            protocol\n        }\n    }\n": typeof types.ConnectorTagDataDocument,
    "\n    query DataPlanes($after: String) {\n        dataPlanes(first: 100, after: $after) {\n            edges {\n                node {\n                    name\n                    cloudProvider\n                    region\n                    isPublic\n                    fqdn\n                    cidrBlocks\n                    awsIamUserArn\n                    gcpServiceAccountEmail\n                    azureApplicationClientId\n                    azureApplicationName\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n": typeof types.DataPlanesDocument,
    "\n    query InviteLinks($first: Int, $after: String) {\n        inviteLinks(first: $first, after: $after) {\n            edges {\n                node {\n                    token\n                    ssoProviderId\n                    catalogPrefix\n                    capability\n                    singleUse\n                    detail\n                    createdAt\n                }\n                cursor\n            }\n            pageInfo {\n                ...PageInfoFields\n            }\n        }\n    }\n": typeof types.InviteLinksDocument,
    "\n    mutation CreateInviteLink(\n        $catalogPrefix: Prefix!\n        $capability: Capability!\n        $singleUse: Boolean!\n        $detail: String\n    ) {\n        createInviteLink(\n            catalogPrefix: $catalogPrefix\n            capability: $capability\n            singleUse: $singleUse\n            detail: $detail\n        ) {\n            token\n            catalogPrefix\n            capability\n            singleUse\n            detail\n            createdAt\n        }\n    }\n": typeof types.CreateInviteLinkDocument,
    "\n    mutation DeleteInviteLink($token: UUID!) {\n        deleteInviteLink(token: $token)\n    }\n": typeof types.DeleteInviteLinkDocument,
    "\n    mutation RedeemInviteLink($token: UUID!) {\n        redeemInviteLink(token: $token) {\n            capability\n            catalogPrefix\n        }\n    }\n": typeof types.RedeemInviteLinkDocument,
    "\n    query LiveSpecsQuery($prefix: Prefix!, $after: String) {\n        liveSpecs(by: { prefix: $prefix }, first: 100, after: $after) {\n            edges {\n                cursor\n                node {\n                    catalogName\n                    liveSpec {\n                        catalogType\n                    }\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n": typeof types.LiveSpecsQueryDocument,
    "\n    mutation CreateStorageMapping(\n        $catalogPrefix: Prefix!\n        $spec: JSON!\n        $detail: String\n    ) {\n        createStorageMapping(\n            catalogPrefix: $catalogPrefix\n            spec: $spec\n            detail: $detail\n        ) {\n            catalogPrefix\n        }\n    }\n": typeof types.CreateStorageMappingDocument,
    "\n    mutation UpdateStorageMapping(\n        $catalogPrefix: Prefix!\n        $spec: JSON!\n        $detail: String\n    ) {\n        updateStorageMapping(\n            catalogPrefix: $catalogPrefix\n            spec: $spec\n            detail: $detail\n        ) {\n            catalogPrefix\n            republish\n        }\n    }\n": typeof types.UpdateStorageMappingDocument,
    "\n    mutation TestConnectionHealth($catalogPrefix: Prefix!, $spec: JSON!) {\n        testConnectionHealth(catalogPrefix: $catalogPrefix, spec: $spec) {\n            results {\n                fragmentStore\n                dataPlaneName\n                error\n            }\n        }\n    }\n": typeof types.TestConnectionHealthDocument,
    "\n    query StorageMappingQuery($underPrefix: Prefix!) {\n        storageMappings(by: { underPrefix: $underPrefix }) {\n            edges {\n                cursor\n                node {\n                    catalogPrefix\n                    spec\n                }\n            }\n        }\n    }\n": typeof types.StorageMappingQueryDocument,
    "\n    query AlertingOverviewQuery($prefix: String!, $active: Boolean) {\n        alerts(by: { prefix: $prefix, active: $active }) {\n            edges {\n                node {\n                    alertType\n                    firedAt\n                    catalogName\n                    alertDetails: arguments\n                    resolvedAt\n                }\n            }\n        }\n    }\n": typeof types.AlertingOverviewQueryDocument,
    "\n    query ActiveAlertCount($catalogName: Name!) {\n        liveSpecs(by: { names: [$catalogName] }) {\n            edges {\n                cursor\n                node {\n                    activeAlerts {\n                        alertType\n                    }\n                }\n            }\n        }\n    }\n": typeof types.ActiveAlertCountDocument,
    "\n    query ActiveAlertsQuery($catalogName: [Name!]) {\n        liveSpecs(by: { names: $catalogName }) {\n            edges {\n                node {\n                    activeAlerts {\n                        alertType\n                        catalogName\n                        alertDetails: arguments\n                        firedAt\n                    }\n                }\n            }\n        }\n    }\n": typeof types.ActiveAlertsQueryDocument,
    "\n    query AlertHistoryQuery(\n        $catalogName: [Name!]\n        $before: String\n        $last: Int!\n    ) {\n        liveSpecs(by: { names: $catalogName }) {\n            edges {\n                node {\n                    alertHistory(before: $before, last: $last) {\n                        edges {\n                            cursor\n                            node {\n                                alertType\n                                alertDetails: arguments\n                                catalogName\n                                firedAt\n                                resolvedAt\n                            }\n                        }\n                        pageInfo {\n                            ...PageInfoFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n    \n": typeof types.AlertHistoryQueryDocument,
    "\n    fragment PageInfoFields on PageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n    }\n": typeof types.PageInfoFieldsFragmentDoc,
    "\n    query AuthRolesQuery($after: String) {\n        prefixes(by: { minCapability: read }, first: 7500, after: $after) {\n            edges {\n                node {\n                    prefix\n                    userCapability\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n": typeof types.AuthRolesQueryDocument,
};
const documents: Documents = {
    "\n    mutation CreateAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n        $alertTypes: [AlertType!]\n        $detail: String\n    ) {\n        createAlertSubscription(\n            prefix: $prefix\n            email: $email\n            alertTypes: $alertTypes\n            detail: $detail\n        ) {\n            catalogPrefix\n            email\n        }\n    }\n": types.CreateAlertSubscriptionMutationDocument,
    "\n    mutation DeleteAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n    ) {\n        deleteAlertSubscription(prefix: $prefix, email: $email) {\n            catalogPrefix\n            email\n        }\n    }\n": types.DeleteAlertSubscriptionMutationDocument,
    "\n    query AlertSubscriptions($prefix: Prefix!) {\n        alertSubscriptions(by: { prefix: $prefix }) {\n            alertTypes\n            catalogPrefix\n            email\n            updatedAt\n        }\n    }\n": types.AlertSubscriptionsDocument,
    "\n    mutation UpdateAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n        $alertTypes: [AlertType!]\n        $detail: String\n    ) {\n        updateAlertSubscription(\n            prefix: $prefix\n            email: $email\n            alertTypes: $alertTypes\n            detail: $detail\n        ) {\n            catalogPrefix\n            email\n        }\n    }\n": types.UpdateAlertSubscriptionMutationDocument,
    "\n    query AlertType {\n        alertTypes {\n            alertType\n            description\n            displayName\n            isDefault\n            isSystem\n        }\n    }\n": types.AlertTypeDocument,
    "\n    query ConnectorsGrid($filter: ConnectorsFilter, $after: String) {\n        connectors(first: 500, after: $after, filter: $filter) {\n            edges {\n                cursor\n                node {\n                    id\n                    imageName\n                    logoUrl\n                    title\n                    recommended\n                    shortDescription\n                    defaultSpec {\n                        id\n                        imageTag\n                        documentationUrl\n                        protocol\n                    }\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n": types.ConnectorsGridDocument,
    "\n    query ConnectorTagData($imageName: String!, $fullImageName: String!) {\n        connector(imageName: $imageName) {\n            id\n            imageName\n            logoUrl\n            title\n        }\n        connectorSpec(fullImageName: $fullImageName) {\n            id\n            imageTag\n            defaultCaptureInterval\n            disableBackfill\n            documentationUrl\n            endpointSpecSchema\n            resourceSpecSchema\n            protocol\n        }\n    }\n": types.ConnectorTagDataDocument,
    "\n    query DataPlanes($after: String) {\n        dataPlanes(first: 100, after: $after) {\n            edges {\n                node {\n                    name\n                    cloudProvider\n                    region\n                    isPublic\n                    fqdn\n                    cidrBlocks\n                    awsIamUserArn\n                    gcpServiceAccountEmail\n                    azureApplicationClientId\n                    azureApplicationName\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n": types.DataPlanesDocument,
    "\n    query InviteLinks($first: Int, $after: String) {\n        inviteLinks(first: $first, after: $after) {\n            edges {\n                node {\n                    token\n                    ssoProviderId\n                    catalogPrefix\n                    capability\n                    singleUse\n                    detail\n                    createdAt\n                }\n                cursor\n            }\n            pageInfo {\n                ...PageInfoFields\n            }\n        }\n    }\n": types.InviteLinksDocument,
    "\n    mutation CreateInviteLink(\n        $catalogPrefix: Prefix!\n        $capability: Capability!\n        $singleUse: Boolean!\n        $detail: String\n    ) {\n        createInviteLink(\n            catalogPrefix: $catalogPrefix\n            capability: $capability\n            singleUse: $singleUse\n            detail: $detail\n        ) {\n            token\n            catalogPrefix\n            capability\n            singleUse\n            detail\n            createdAt\n        }\n    }\n": types.CreateInviteLinkDocument,
    "\n    mutation DeleteInviteLink($token: UUID!) {\n        deleteInviteLink(token: $token)\n    }\n": types.DeleteInviteLinkDocument,
    "\n    mutation RedeemInviteLink($token: UUID!) {\n        redeemInviteLink(token: $token) {\n            capability\n            catalogPrefix\n        }\n    }\n": types.RedeemInviteLinkDocument,
    "\n    query LiveSpecsQuery($prefix: Prefix!, $after: String) {\n        liveSpecs(by: { prefix: $prefix }, first: 100, after: $after) {\n            edges {\n                cursor\n                node {\n                    catalogName\n                    liveSpec {\n                        catalogType\n                    }\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n": types.LiveSpecsQueryDocument,
    "\n    mutation CreateStorageMapping(\n        $catalogPrefix: Prefix!\n        $spec: JSON!\n        $detail: String\n    ) {\n        createStorageMapping(\n            catalogPrefix: $catalogPrefix\n            spec: $spec\n            detail: $detail\n        ) {\n            catalogPrefix\n        }\n    }\n": types.CreateStorageMappingDocument,
    "\n    mutation UpdateStorageMapping(\n        $catalogPrefix: Prefix!\n        $spec: JSON!\n        $detail: String\n    ) {\n        updateStorageMapping(\n            catalogPrefix: $catalogPrefix\n            spec: $spec\n            detail: $detail\n        ) {\n            catalogPrefix\n            republish\n        }\n    }\n": types.UpdateStorageMappingDocument,
    "\n    mutation TestConnectionHealth($catalogPrefix: Prefix!, $spec: JSON!) {\n        testConnectionHealth(catalogPrefix: $catalogPrefix, spec: $spec) {\n            results {\n                fragmentStore\n                dataPlaneName\n                error\n            }\n        }\n    }\n": types.TestConnectionHealthDocument,
    "\n    query StorageMappingQuery($underPrefix: Prefix!) {\n        storageMappings(by: { underPrefix: $underPrefix }) {\n            edges {\n                cursor\n                node {\n                    catalogPrefix\n                    spec\n                }\n            }\n        }\n    }\n": types.StorageMappingQueryDocument,
    "\n    query AlertingOverviewQuery($prefix: String!, $active: Boolean) {\n        alerts(by: { prefix: $prefix, active: $active }) {\n            edges {\n                node {\n                    alertType\n                    firedAt\n                    catalogName\n                    alertDetails: arguments\n                    resolvedAt\n                }\n            }\n        }\n    }\n": types.AlertingOverviewQueryDocument,
    "\n    query ActiveAlertCount($catalogName: Name!) {\n        liveSpecs(by: { names: [$catalogName] }) {\n            edges {\n                cursor\n                node {\n                    activeAlerts {\n                        alertType\n                    }\n                }\n            }\n        }\n    }\n": types.ActiveAlertCountDocument,
    "\n    query ActiveAlertsQuery($catalogName: [Name!]) {\n        liveSpecs(by: { names: $catalogName }) {\n            edges {\n                node {\n                    activeAlerts {\n                        alertType\n                        catalogName\n                        alertDetails: arguments\n                        firedAt\n                    }\n                }\n            }\n        }\n    }\n": types.ActiveAlertsQueryDocument,
    "\n    query AlertHistoryQuery(\n        $catalogName: [Name!]\n        $before: String\n        $last: Int!\n    ) {\n        liveSpecs(by: { names: $catalogName }) {\n            edges {\n                node {\n                    alertHistory(before: $before, last: $last) {\n                        edges {\n                            cursor\n                            node {\n                                alertType\n                                alertDetails: arguments\n                                catalogName\n                                firedAt\n                                resolvedAt\n                            }\n                        }\n                        pageInfo {\n                            ...PageInfoFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n    \n": types.AlertHistoryQueryDocument,
    "\n    fragment PageInfoFields on PageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n    }\n": types.PageInfoFieldsFragmentDoc,
    "\n    query AuthRolesQuery($after: String) {\n        prefixes(by: { minCapability: read }, first: 7500, after: $after) {\n            edges {\n                node {\n                    prefix\n                    userCapability\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n": types.AuthRolesQueryDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n        $alertTypes: [AlertType!]\n        $detail: String\n    ) {\n        createAlertSubscription(\n            prefix: $prefix\n            email: $email\n            alertTypes: $alertTypes\n            detail: $detail\n        ) {\n            catalogPrefix\n            email\n        }\n    }\n"): (typeof documents)["\n    mutation CreateAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n        $alertTypes: [AlertType!]\n        $detail: String\n    ) {\n        createAlertSubscription(\n            prefix: $prefix\n            email: $email\n            alertTypes: $alertTypes\n            detail: $detail\n        ) {\n            catalogPrefix\n            email\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n    ) {\n        deleteAlertSubscription(prefix: $prefix, email: $email) {\n            catalogPrefix\n            email\n        }\n    }\n"): (typeof documents)["\n    mutation DeleteAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n    ) {\n        deleteAlertSubscription(prefix: $prefix, email: $email) {\n            catalogPrefix\n            email\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query AlertSubscriptions($prefix: Prefix!) {\n        alertSubscriptions(by: { prefix: $prefix }) {\n            alertTypes\n            catalogPrefix\n            email\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query AlertSubscriptions($prefix: Prefix!) {\n        alertSubscriptions(by: { prefix: $prefix }) {\n            alertTypes\n            catalogPrefix\n            email\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n        $alertTypes: [AlertType!]\n        $detail: String\n    ) {\n        updateAlertSubscription(\n            prefix: $prefix\n            email: $email\n            alertTypes: $alertTypes\n            detail: $detail\n        ) {\n            catalogPrefix\n            email\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateAlertSubscriptionMutation(\n        $prefix: Prefix!\n        $email: String!\n        $alertTypes: [AlertType!]\n        $detail: String\n    ) {\n        updateAlertSubscription(\n            prefix: $prefix\n            email: $email\n            alertTypes: $alertTypes\n            detail: $detail\n        ) {\n            catalogPrefix\n            email\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query AlertType {\n        alertTypes {\n            alertType\n            description\n            displayName\n            isDefault\n            isSystem\n        }\n    }\n"): (typeof documents)["\n    query AlertType {\n        alertTypes {\n            alertType\n            description\n            displayName\n            isDefault\n            isSystem\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ConnectorsGrid($filter: ConnectorsFilter, $after: String) {\n        connectors(first: 500, after: $after, filter: $filter) {\n            edges {\n                cursor\n                node {\n                    id\n                    imageName\n                    logoUrl\n                    title\n                    recommended\n                    shortDescription\n                    defaultSpec {\n                        id\n                        imageTag\n                        documentationUrl\n                        protocol\n                    }\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n"): (typeof documents)["\n    query ConnectorsGrid($filter: ConnectorsFilter, $after: String) {\n        connectors(first: 500, after: $after, filter: $filter) {\n            edges {\n                cursor\n                node {\n                    id\n                    imageName\n                    logoUrl\n                    title\n                    recommended\n                    shortDescription\n                    defaultSpec {\n                        id\n                        imageTag\n                        documentationUrl\n                        protocol\n                    }\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ConnectorTagData($imageName: String!, $fullImageName: String!) {\n        connector(imageName: $imageName) {\n            id\n            imageName\n            logoUrl\n            title\n        }\n        connectorSpec(fullImageName: $fullImageName) {\n            id\n            imageTag\n            defaultCaptureInterval\n            disableBackfill\n            documentationUrl\n            endpointSpecSchema\n            resourceSpecSchema\n            protocol\n        }\n    }\n"): (typeof documents)["\n    query ConnectorTagData($imageName: String!, $fullImageName: String!) {\n        connector(imageName: $imageName) {\n            id\n            imageName\n            logoUrl\n            title\n        }\n        connectorSpec(fullImageName: $fullImageName) {\n            id\n            imageTag\n            defaultCaptureInterval\n            disableBackfill\n            documentationUrl\n            endpointSpecSchema\n            resourceSpecSchema\n            protocol\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query DataPlanes($after: String) {\n        dataPlanes(first: 100, after: $after) {\n            edges {\n                node {\n                    name\n                    cloudProvider\n                    region\n                    isPublic\n                    fqdn\n                    cidrBlocks\n                    awsIamUserArn\n                    gcpServiceAccountEmail\n                    azureApplicationClientId\n                    azureApplicationName\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n"): (typeof documents)["\n    query DataPlanes($after: String) {\n        dataPlanes(first: 100, after: $after) {\n            edges {\n                node {\n                    name\n                    cloudProvider\n                    region\n                    isPublic\n                    fqdn\n                    cidrBlocks\n                    awsIamUserArn\n                    gcpServiceAccountEmail\n                    azureApplicationClientId\n                    azureApplicationName\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query InviteLinks($first: Int, $after: String) {\n        inviteLinks(first: $first, after: $after) {\n            edges {\n                node {\n                    token\n                    ssoProviderId\n                    catalogPrefix\n                    capability\n                    singleUse\n                    detail\n                    createdAt\n                }\n                cursor\n            }\n            pageInfo {\n                ...PageInfoFields\n            }\n        }\n    }\n"): (typeof documents)["\n    query InviteLinks($first: Int, $after: String) {\n        inviteLinks(first: $first, after: $after) {\n            edges {\n                node {\n                    token\n                    ssoProviderId\n                    catalogPrefix\n                    capability\n                    singleUse\n                    detail\n                    createdAt\n                }\n                cursor\n            }\n            pageInfo {\n                ...PageInfoFields\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateInviteLink(\n        $catalogPrefix: Prefix!\n        $capability: Capability!\n        $singleUse: Boolean!\n        $detail: String\n    ) {\n        createInviteLink(\n            catalogPrefix: $catalogPrefix\n            capability: $capability\n            singleUse: $singleUse\n            detail: $detail\n        ) {\n            token\n            catalogPrefix\n            capability\n            singleUse\n            detail\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    mutation CreateInviteLink(\n        $catalogPrefix: Prefix!\n        $capability: Capability!\n        $singleUse: Boolean!\n        $detail: String\n    ) {\n        createInviteLink(\n            catalogPrefix: $catalogPrefix\n            capability: $capability\n            singleUse: $singleUse\n            detail: $detail\n        ) {\n            token\n            catalogPrefix\n            capability\n            singleUse\n            detail\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteInviteLink($token: UUID!) {\n        deleteInviteLink(token: $token)\n    }\n"): (typeof documents)["\n    mutation DeleteInviteLink($token: UUID!) {\n        deleteInviteLink(token: $token)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation RedeemInviteLink($token: UUID!) {\n        redeemInviteLink(token: $token) {\n            capability\n            catalogPrefix\n        }\n    }\n"): (typeof documents)["\n    mutation RedeemInviteLink($token: UUID!) {\n        redeemInviteLink(token: $token) {\n            capability\n            catalogPrefix\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query LiveSpecsQuery($prefix: Prefix!, $after: String) {\n        liveSpecs(by: { prefix: $prefix }, first: 100, after: $after) {\n            edges {\n                cursor\n                node {\n                    catalogName\n                    liveSpec {\n                        catalogType\n                    }\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n"): (typeof documents)["\n    query LiveSpecsQuery($prefix: Prefix!, $after: String) {\n        liveSpecs(by: { prefix: $prefix }, first: 100, after: $after) {\n            edges {\n                cursor\n                node {\n                    catalogName\n                    liveSpec {\n                        catalogType\n                    }\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateStorageMapping(\n        $catalogPrefix: Prefix!\n        $spec: JSON!\n        $detail: String\n    ) {\n        createStorageMapping(\n            catalogPrefix: $catalogPrefix\n            spec: $spec\n            detail: $detail\n        ) {\n            catalogPrefix\n        }\n    }\n"): (typeof documents)["\n    mutation CreateStorageMapping(\n        $catalogPrefix: Prefix!\n        $spec: JSON!\n        $detail: String\n    ) {\n        createStorageMapping(\n            catalogPrefix: $catalogPrefix\n            spec: $spec\n            detail: $detail\n        ) {\n            catalogPrefix\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation UpdateStorageMapping(\n        $catalogPrefix: Prefix!\n        $spec: JSON!\n        $detail: String\n    ) {\n        updateStorageMapping(\n            catalogPrefix: $catalogPrefix\n            spec: $spec\n            detail: $detail\n        ) {\n            catalogPrefix\n            republish\n        }\n    }\n"): (typeof documents)["\n    mutation UpdateStorageMapping(\n        $catalogPrefix: Prefix!\n        $spec: JSON!\n        $detail: String\n    ) {\n        updateStorageMapping(\n            catalogPrefix: $catalogPrefix\n            spec: $spec\n            detail: $detail\n        ) {\n            catalogPrefix\n            republish\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation TestConnectionHealth($catalogPrefix: Prefix!, $spec: JSON!) {\n        testConnectionHealth(catalogPrefix: $catalogPrefix, spec: $spec) {\n            results {\n                fragmentStore\n                dataPlaneName\n                error\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation TestConnectionHealth($catalogPrefix: Prefix!, $spec: JSON!) {\n        testConnectionHealth(catalogPrefix: $catalogPrefix, spec: $spec) {\n            results {\n                fragmentStore\n                dataPlaneName\n                error\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query StorageMappingQuery($underPrefix: Prefix!) {\n        storageMappings(by: { underPrefix: $underPrefix }) {\n            edges {\n                cursor\n                node {\n                    catalogPrefix\n                    spec\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query StorageMappingQuery($underPrefix: Prefix!) {\n        storageMappings(by: { underPrefix: $underPrefix }) {\n            edges {\n                cursor\n                node {\n                    catalogPrefix\n                    spec\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query AlertingOverviewQuery($prefix: String!, $active: Boolean) {\n        alerts(by: { prefix: $prefix, active: $active }) {\n            edges {\n                node {\n                    alertType\n                    firedAt\n                    catalogName\n                    alertDetails: arguments\n                    resolvedAt\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query AlertingOverviewQuery($prefix: String!, $active: Boolean) {\n        alerts(by: { prefix: $prefix, active: $active }) {\n            edges {\n                node {\n                    alertType\n                    firedAt\n                    catalogName\n                    alertDetails: arguments\n                    resolvedAt\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ActiveAlertCount($catalogName: Name!) {\n        liveSpecs(by: { names: [$catalogName] }) {\n            edges {\n                cursor\n                node {\n                    activeAlerts {\n                        alertType\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query ActiveAlertCount($catalogName: Name!) {\n        liveSpecs(by: { names: [$catalogName] }) {\n            edges {\n                cursor\n                node {\n                    activeAlerts {\n                        alertType\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query ActiveAlertsQuery($catalogName: [Name!]) {\n        liveSpecs(by: { names: $catalogName }) {\n            edges {\n                node {\n                    activeAlerts {\n                        alertType\n                        catalogName\n                        alertDetails: arguments\n                        firedAt\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query ActiveAlertsQuery($catalogName: [Name!]) {\n        liveSpecs(by: { names: $catalogName }) {\n            edges {\n                node {\n                    activeAlerts {\n                        alertType\n                        catalogName\n                        alertDetails: arguments\n                        firedAt\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query AlertHistoryQuery(\n        $catalogName: [Name!]\n        $before: String\n        $last: Int!\n    ) {\n        liveSpecs(by: { names: $catalogName }) {\n            edges {\n                node {\n                    alertHistory(before: $before, last: $last) {\n                        edges {\n                            cursor\n                            node {\n                                alertType\n                                alertDetails: arguments\n                                catalogName\n                                firedAt\n                                resolvedAt\n                            }\n                        }\n                        pageInfo {\n                            ...PageInfoFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n    \n"): (typeof documents)["\n    query AlertHistoryQuery(\n        $catalogName: [Name!]\n        $before: String\n        $last: Int!\n    ) {\n        liveSpecs(by: { names: $catalogName }) {\n            edges {\n                node {\n                    alertHistory(before: $before, last: $last) {\n                        edges {\n                            cursor\n                            node {\n                                alertType\n                                alertDetails: arguments\n                                catalogName\n                                firedAt\n                                resolvedAt\n                            }\n                        }\n                        pageInfo {\n                            ...PageInfoFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n    \n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment PageInfoFields on PageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n    }\n"): (typeof documents)["\n    fragment PageInfoFields on PageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query AuthRolesQuery($after: String) {\n        prefixes(by: { minCapability: read }, first: 7500, after: $after) {\n            edges {\n                node {\n                    prefix\n                    userCapability\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n"): (typeof documents)["\n    query AuthRolesQuery($after: String) {\n        prefixes(by: { minCapability: read }, first: 7500, after: $after) {\n            edges {\n                node {\n                    prefix\n                    userCapability\n                }\n            }\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;