import type {
    DocumentNode,
    GraphQLOutputType,
    GraphQLSchema,
    SelectionSetNode,
} from 'graphql';

import {
    buildSchema,
    getNamedType,
    isInterfaceType,
    isObjectType,
} from 'graphql';

// The GraphQL scalar the backend uses for values that must never reach a
// language model (bearer secrets, client secrets, etc.). This is the source of
// truth — annotate a field `: Sensitive!` and it's redacted automatically.
const SENSITIVE_SCALAR = 'Sensitive';

const REDACTED = '[redacted — shown to the user only, withheld from the assistant]';

// Schema-independent safety net: even if the schema is unavailable or a field
// isn't yet typed `Sensitive`, never hand the model a value under one of these
// keys. Deliberately conservative to avoid over-redacting (e.g. "tokenCount").
const SENSITIVE_NAME = /(^|_)(secret|password|credential|privatekey|apikey)/i;

// The full SDL (already generated by codegen) is loaded lazily and cached, so it
// stays out of the main bundle and is only fetched the first time a tool returns
// data to the model.
let schemaPromise: Promise<GraphQLSchema | null> | null = null;

const loadSchema = (): Promise<GraphQLSchema | null> => {
    if (!schemaPromise) {
        schemaPromise = import('../../gql-types/schema.graphql?raw')
            .then((module) => buildSchema(module.default))
            .catch(() => null);
    }
    return schemaPromise;
};

// Name-based deep redaction — the schema-independent backstop.
const deepNameRedact = (node: any): void => {
    if (Array.isArray(node)) {
        node.forEach(deepNameRedact);
        return;
    }
    if (node && typeof node === 'object') {
        for (const key of Object.keys(node)) {
            if (typeof node[key] === 'string' && SENSITIVE_NAME.test(key)) {
                node[key] = REDACTED;
            } else {
                deepNameRedact(node[key]);
            }
        }
    }
};

// Schema-driven redaction: walk the operation's selection set against the schema
// and redact any selected field whose (unwrapped) type is the Sensitive scalar.
const redactSelectionSet = (
    selectionSet: SelectionSetNode,
    parentType: GraphQLOutputType,
    data: any
): void => {
    const namedParent = getNamedType(parentType);
    if (
        (!isObjectType(namedParent) && !isInterfaceType(namedParent)) ||
        data == null ||
        typeof data !== 'object'
    ) {
        return;
    }

    const fields = namedParent.getFields();
    for (const selection of selectionSet.selections) {
        // Field selections only — fragments are caught by the name-based net.
        if (selection.kind !== 'Field') {
            continue;
        }

        const fieldDef = fields[selection.name.value];
        if (!fieldDef) {
            continue;
        }

        const responseKey = selection.alias?.value ?? selection.name.value;

        if (getNamedType(fieldDef.type).name === SENSITIVE_SCALAR) {
            if (data[responseKey] != null) {
                data[responseKey] = REDACTED;
            }
            continue;
        }

        if (selection.selectionSet) {
            const child = data[responseKey];
            const recurse = (value: any) =>
                redactSelectionSet(
                    selection.selectionSet as SelectionSetNode,
                    fieldDef.type,
                    value
                );
            if (Array.isArray(child)) {
                child.forEach(recurse);
            } else {
                recurse(child);
            }
        }
    }
};

// Returns a deep copy of a GraphQL `data` object with every Sensitive-typed (or
// sensitively-named) field replaced by a placeholder — safe to hand to the LLM.
// The original is left untouched so the UI can still show real values to the
// user. This is the single choke-point every data-returning tool routes through.
export const redactForModel = async (
    data: unknown,
    operation: DocumentNode
): Promise<unknown> => {
    if (data == null || typeof data !== 'object') {
        return data;
    }

    const clone = structuredClone(data);

    try {
        const schema = await loadSchema();
        const operationDef = operation.definitions.find(
            (definition) => definition.kind === 'OperationDefinition'
        );

        if (schema && operationDef && 'operation' in operationDef) {
            const rootType =
                operationDef.operation === 'mutation'
                    ? schema.getMutationType()
                    : operationDef.operation === 'subscription'
                      ? schema.getSubscriptionType()
                      : schema.getQueryType();

            if (rootType) {
                redactSelectionSet(operationDef.selectionSet, rootType, clone);
            }
        }
    } catch {
        // Fall through to the name-based net below.
    }

    // Always run the name-based net too — defense in depth for anything the
    // schema walk missed (fragments, untyped-but-named secrets).
    deepNameRedact(clone);

    return clone;
};
